### ISSUE TITLE
Returning a null value 

### ISSUE THREAD

**Issue by braglin** [dpa99c/cordova-plugin-crosswalk-data-migration#2]
Hi!

I believe I'm doing something wrong, I'm updating my app but I can't access the localStorage items...

This is my plugin list:

    com.phonegap.plugins.speech 1.0.0 "XSpeechRecognizer"
    cordova-admobsdk 1.0.4 "Google Mobile Ads SDK for Cordova"
    cordova-plugin-admob 3.2.4 "Cordova-Phonegap AdMob Plugin"
    cordova-plugin-app-event 1.2.1 "Application Events"
    cordova-plugin-crosswalk-data-migration 1.0.0 "Crosswalk Data Migration Plugin"
    cordova-plugin-device 1.1.6 "Device"
    cordova-plugin-market 1.2.0 "Market"
    cordova-plugin-tts 0.2.3 "TTS"
    cordova-plugin-whitelist 1.3.2 "Whitelist"
    cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
    com.phonegap.plugins.speech 1.0.0 "XSpeechRecognizer"
    de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
    es6-promise-plugin 4.1.0 "Promise"`

First I removed the Crosswalk plugin (cordova-plugin-crosswalk-webview ^2.3.0), then removed the android platform & add again, I added the migration plugin. I think it's right!

But If I try read the storaged item... for example:
    
    console.log(localStorage.getItem('langNat');
it's returning a **_null_** value...

Any idea about it?

**Comment by dpa99c** [comment]
Just to confirm:
- You have an existing installed app which uses Crosswalk and contains local storage data
- You added this plugin, removed the Crosswalk plugin, re-added the Android platform, incremented the build number
- You re-built the APK and installed it as an update over the existing app
- a value that was previously present in local storage in the Crosswalk version is now not present in the updated version?

So: 

- What version of Android are you testing on?
- If you use Chrome Dev Tools to connect to the app webview, do you see any local storage data?

**Comment by braglin** [comment]
Thank you for the quickly support!

> You have an existing installed app which uses Crosswalk and contains local storage data
> You added this plugin, removed the Crosswalk plugin, re-added the Android platform, incremented the build number
> You re-built the APK and installed it as an update over the existing app
> a value that was previously present in local storage in the Crosswalk version is now not present in the updated version?

Actually first I removed the crosswalk plugin and then I added this plugin.... does it matter?
Yes... I'm installing this as an update...
Right, the value is not present...

> What version of Android are you testing on?
If you use Chrome Dev Tools to connect to the app webview, do you see any local storage data?

I'm using a XT1033 (Moto G) and a G530-BT (Samsung Prime Duos)... Android 5.1 and 5.0.2 respectively!
In Chrome Dev Tools inspector the Local Storage is empty... there's no entries....

**Comment by dpa99c** [comment]
I'd suggest trying the [example](https://github.com/dpa99c/cordova-plugin-crosswalk-data-migration#example-app) on your target devices to see if it works. I've only tested this on a limited range of devices, so it might be that a different manufacturer is the cause of the issue. You don't have to build the project yourself if you don't want, you can use install the pre-built APKs.

**Comment by braglin** [comment]
It works!

As I said, probably I'm doing something wrong.... 

I also update the Android SDK version to the latest one... does it matter???

**Comment by dpa99c** [comment]
Android SDK version shouldn't matter. 
You should be able to use the example as a reference to figure out what's wrong in your case.
