### ISSUE TITLE
Not migrating localStorage data

### ISSUE THREAD

**Issue by mcfarljw** [dpa99c/cordova-plugin-crosswalk-data-migration#4]
**I'm submitting a ...**  (check one with "x"):
- [ x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

I've got a few apps using the cordova crosswalk 2.3.0 plugin on Android and when I use this plugin after removing crosswalk it doesn't migrate my localStorage data (but does migrate my indexedDB stuff).

**Expected behavior:**

I expect that the plugin will migrate both localStorage and indexedDB.

**Environment information**

Cordova 8.0.0
macOS High Sierra 10.13.6
Samsung Galaxy Note 8 (Android 8.0)
OnePlus One (Android 6.0.1)
Node v8.11.3

After looking through the plugin code my only thoughts are that `modernLocalStorageDir ` and `oldLocalStorageDir` might not be all the possible locations anymore?

**Comment by dpa99c** [comment]
I've just regression tested the [example app](https://github.com/dpa99c/cordova-plugin-crosswalk-data-migration#example-app) on Android 8.1.0 with `cordova@8.0.0` and `cordova-android@7.1.1` and migration of local storage worked OK.

Please try the example app migration on your target devices and confirm whether the local storage value was migrated.


<img width="320" src="https://user-images.githubusercontent.com/2345062/43959054-6670075a-9ca5-11e8-953f-3d42f1437418.png" />

**Comment by mcfarljw** [comment]
I just tested the example migration apps and they both worked as intended. I guess it might be some other plugin I'm using that is causing a conflict, so I'll need to start systematically disabling some of those.

I did notice that the latest version of `cordova-plugin-ionic-webview@2.0.2` which was initially only for iOS added in some Android stuff which prevents anything from being migrated.

**Comment by dpa99c** [comment]
Closing as the plugin was validated by the example app

**Comment by fmtoffolo** [comment]
Is it planned to also migrate to ionic webview?
