### ISSUE TITLE
Migrates data, but have to manually restart app?

### ISSUE THREAD

**Issue by cyborgk9** [dpa99c/cordova-plugin-crosswalk-data-migration#7]
**I'm submitting a ...**  (check one with "x"):
- [X] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

I am trying to remove Crosswalk from my app while retaining the localstorage.

After following the steps in the readme, I can make a build that runs, but the first run does not have the stored data - it's as if the app was being run for the first time. Closing the app and restarting it then has the data... sometimes. Other times I have to do a fresh "cordova run android --device" before it seems to 'take'.

I cannot run the example projects in cordova 8.0.1 - I get the following error when I try to add the 'android' platform:

`"Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it."`

...however, based on the .java source, it feels like the application.restart() isn't getting run?

**Expected behavior:**

The app should carry over the saved localstorage data on the first run of the new build.

**Steps to reproduce:**

N/A

**Environment information**

- Cordova CLI version : 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version: android 8.1.0
- Plugins & versions installed in project (including this plugin)

cc.fovea.cordova.purchase 8.1.1 "Purchase"
com.commontime.cordova.splitscreen 1.2.0 "SplitScreen"
cordova-android-support-gradle-release 3.0.0 "cordova-android-support-gradle-release"
cordova-build-architecture 1.0.4 "Build Architecture"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.3.0 "AppRate"
cordova-plugin-crosswalk-data-migration 1.0.0 "Crosswalk Data Migration Plugin"
cordova-plugin-crypt-file 1.3.3 "CordovaCrypt"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-hide-home-indicator 1.0.0 "Hide Home Indicator"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ios-longpress-fix 1.1.0 "iOS LongPress Fix"
cordova-plugin-network-information 3.0.0-dev "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 6.0.1-dev "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-plugin-yanap 0.8.9 "Yanap"
es6-promise-plugin 4.2.2 "Promise"
org.apache.cordova.pointerevents 0.1.0 "PointerEvents"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

- Dev machine OS and version, e.g.
ProductName: Mac OS X
ProductVersion: 10.15.5
BuildVersion:	19F96

**Other information:**

The plugin 'readme' describes "the plugin restarts the Cordova activity" after performing its operations, but that doesn't seem to be happening. I don't know how to insert alerts or something into the Java to test how far it's going along the 'run'/migrate process, though, to verify... sorry.

It might be nice to have Javascript functions I can use on 'ready'... like:

> crosswalkMigrate.hasData(function() {
>    alert("Have old Crosswalk data, about to migrate...");
>    crosswalkMigrate.performMigration();   // performs migration and restarts app
> });

... if only so I can verify better what it's doing?  Alternately, if you can help me add some alerts to the existing .java code that might help me figure out if it's running correctly?

If you can help I'd appreciate it. :)
Thanks!

**Comment by Luro91** [comment]
I also have this issue. I also tested the builds from the example project:
https://github.com/dpa99c/cordova-plugin-crosswalk-data-migration-test-part1/tree/master/build
https://github.com/dpa99c/cordova-plugin-crosswalk-data-migration-test-part2/tree/master/build

According to the logs the restart should be called, but somehow the data is only available when restarting the app manually.

```
2020-08-19 11:37:12.241 11833-11833/io.cordova.hellocordova D/Migration: initialize()
2020-08-19 11:37:12.242 11833-11833/io.cordova.hellocordova D/Migration: running Crosswalk migration shim
2020-08-19 11:37:12.242 11833-11833/io.cordova.hellocordova D/Migration: exists '/data/user/0/io.cordova.hellocordova/app_xwalkcore/Default: true
2020-08-19 11:37:12.242 11833-11833/io.cordova.hellocordova D/Migration: found Crosswalk directory
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: exists '/data/user/0/io.cordova.hellocordova/app_xwalkcore/Default/Local Storage: true
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: Local Storage data found
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: Moved Local Storage from XWalk to System Webview
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: exists '/data/user/0/io.cordova.hellocordova/app_xwalkcore/Default/Cache: false
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: exists '/data/user/0/io.cordova.hellocordova/app_xwalkcore/Default/Cookies: true
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: Moved Cookies from XWalk to System Webview
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: exists '/data/user/0/io.cordova.hellocordova/app_xwalkcore/Default/Cookies-journal: true
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: Moved Cookies-journal from XWalk to System Webview
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: exists '/data/user/0/io.cordova.hellocordova/app_xwalkcore/Default/IndexedDB: true
2020-08-19 11:37:12.243 11833-11833/io.cordova.hellocordova D/Migration: Moved IndexedDB from XWalk to System Webview
2020-08-19 11:37:12.244 11833-11833/io.cordova.hellocordova D/Migration: exists '/data/user/0/io.cordova.hellocordova/app_xwalkcore/Default/databases: true
2020-08-19 11:37:12.244 11833-11833/io.cordova.hellocordova D/Migration: Moved databases from XWalk to System Webview
2020-08-19 11:37:12.245 11833-11833/io.cordova.hellocordova D/Migration: restarting Cordova activity
2020-08-19 11:37:12.390 11833-11833/io.cordova.hellocordova D/Migration: initialize()
```

Tested on Pixel 3a with Android 10 and in the Emulator with Android 11

**Comment by dpa99c** [comment]
It was certainly the case that this worked when I created this plugin: restarting the Cordova activity was sufficient to cause it to be able to read the moved data from the System webview.
However that was more than 3 years ago so it may be that in newer Android versions this no longer works.
As a workaround, you can try using the [`restart()` function](https://github.com/dpa99c/cordova-diagnostic-plugin#restart) from [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) and set the `cold` flag:

    cordova.plugins.diagnostic.restart(onError, true);

This will perform a full application restart. 

Let me know if that works and I can port that cold restart code back to this plugin.

**Comment by cyborgk9** [comment]
Thanks @dpa99c!

I wasn't able to compile my app with cordova-diagnostic-plugin installed for some reason; however I copied the "doColdRestart()" function into Migration.java and called it instead of activity.recreate();. (I had to make a few other edits to the function and do some extra imports to get it to compile).

But, yes - the app shuts down fully it seems, although it didn't restart automatically for me. Maybe I was using the wrong Context ('c') in my attempt (I was using activity.getApplicationContext(), as used in the Migration.java's "initialize" function)...? I'm not really sure about that side of things). 

Regardless, after relaunching the app manually, all the data was fully migrated.

So that seems like it'll work, if you can properly implement the actual 'restart'. :)

Thank you again!

**Comment by Luro91** [comment]
I can also confirm that it works when the cold restart function is used https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L691

**Comment by cujo30227** [comment]
Hi,
I had the same problem with my Cordova app, and also solved it with inserting the doColdRestart() in Migration.java
Thanks

**Comment by cyborgk9** [comment]
Hi  @cujo30227,

> I had the same problem with my Cordova app, and also solved it with inserting the doColdRestart() in Migration.java

Could you share the line(s) you used? I'm not sure how to properly call it... I know it needs to go in place of 'activity.recreate();'. Did you include the cordova-diagnostic-plugin and call the function from that, or copy parts of Diagnostic.java into Migration.java...?

(Calling just "doColdRestart()" gives me a 'cannot find symbol' compilation error... so I assume I need a namespace or something...)

Thanks!

**Comment by arielectron** [comment]
Hi @dpa99c.
Can you merge my PR for fix that? i tested and it works fine.
Bye

**Comment by arielectron** [comment]
#8
